name: simulator_melltoygame
description: UI clone of Mellstroy clicker screen
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  audioplayers: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/streamer.png
    - assets/images/icon.png
    - assets/backgrounds/room_1.png
    - assets/backgrounds/room_2.png
    - assets/backgrounds/room_3.png
    - assets/backgrounds/room_4.png
    - assets/images/silver_coin.png
    - assets/images/gold_coin.png
    - assets/sounds/click_sound.mp3
    - assets/sounds/coin_sound.mp3
    - assets/sounds/background_music.mp3

